services:
  postgres:
    image: postgres:15-alpine
    container_name: ecocapiba-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecocapiba-network
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecocapiba-api
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      CAPIBA_REWARD: ${CAPIBA_REWARD}
      XP_REWARD: ${XP_REWARD}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - ecocapiba-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecocapiba-client
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - ecocapiba-network

volumes:
  postgres_data:

networks:
  ecocapiba-network:
    driver: bridge