version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db-ecocapiba
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecocapiba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/ecocapiba

  backend:
    build: ../../api
    container_name: backend-ecocapiba
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}

  frontend:
    build: ../../client
    container_name: frontend-ecocapiba
    environment:
      VITE_API_URL: ${VITE_API_URL}
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
