export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  transform: {
    '^.+\\.ts$': ['ts-jest', {
      useESM: true,
      tsconfig: {
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
      },
    }],
  },
  moduleNameMapper: {
    '^(\\.\\./)+src/(.*)\\.js$': '<rootDir>/src/$2.ts',
    '^(\\.\\./)+test/(.*)\\.js$': '<rootDir>/test/$2.ts',
    '^(\\.\\./)+helpers/(.*)\\.js$': '<rootDir>/test/helpers/$2.ts',
    '^(\\.\\./)+integration/(.*)\\.js$': '<rootDir>/test/integration/$2.ts',
    '^(\\./)(shared|utils|db|resources|modules)/(.*)\\.js$': '<rootDir>/src/$2/$3.ts',
    '^(\\.\\./)+db/(.*)\\.js$': '<rootDir>/src/db/$2.ts',
    '^(\\.\\./)+resources/(.*)\\.js$': '<rootDir>/src/resources/$2.ts',
    '^(\\.\\./)+middleware/(.*)\\.js$': '<rootDir>/src/middleware/$2.ts',
    '^(\\.\\./)+shared/(.*)\\.js$': '<rootDir>/src/modules/shared/$2.ts',
    '^(\\.\\./)+utils/jwt\\.utils\\.js$': '<rootDir>/test/__mocks__/src/utils/jwt.utils.ts',
    '^(\\.\\./)+utils/(.*)\\.js$': '<rootDir>/src/utils/$2.ts',
    '^(\\.\\./)(shared|utils|db|resources|modules)/(.*)\\.js$': '<rootDir>/src/$2/$3.ts',
    '^(\\./)(AuthRepository|AuthService|AuthController|AuthRoutes)\\.js$': '<rootDir>/src/modules/auth/$2.ts',
    '^(\\./)(RecycleRepository|RecycleService|RecycleController|RecycleRoutes)\\.js$': '<rootDir>/src/modules/recycle/$2.ts',
    '^(\\./)(QuizRepository|QuizService|QuizController|QuizRoutes)\\.js$': '<rootDir>/src/modules/quiz/$2.ts',
    '^(\\./)(routeDecorator|appRoutesDecorator)\\.js$': '<rootDir>/src/resources/decorator/$2.ts',
    '^(\\./)(models)/(.*)\\.js$': '<rootDir>/src/modules/quiz/$2/$3.ts',
    '^(\\./)(QuizAttempt|Question|Quiz|QuizSchema|QuestionSchema|QuizAttemptSchema)\\.js$': '<rootDir>/src/modules/quiz/models/$2.ts',
    '^(\\./)(User|UserSchema)\\.js$': '<rootDir>/src/modules/auth/models/$2.ts',
    '^@prisma/client$': '<rootDir>/test/__mocks__/@prisma/client.ts',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(@prisma/client|@prisma/client/runtime|@prisma/client/runtime/library)/)',
  ],
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  testMatch: [
    '**/test/**/*.test.ts',
    '**/test/**/*.integration.test.ts',
  ],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/models/**',
    '!src/**/enums/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  globals: {
    'jest': true,
  },
};
